package session

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log/slog"
	"slices"
	"strings"
	"sync"

	"github.com/charmbracelet/crush/internal/db"
	"github.com/charmbracelet/crush/internal/event"
	"github.com/charmbracelet/crush/internal/pubsub"
	"github.com/google/uuid"
	"github.com/zeebo/xxh3"
)

type TodoStatus string

const (
	TodoStatusPending    TodoStatus = "pending"
	TodoStatusInProgress TodoStatus = "in_progress"
	TodoStatusCompleted  TodoStatus = "completed"
)

// HashID returns the XXH3 hash of a session ID (UUID) as a hex string.
func HashID(id string) string {
	h := xxh3.New()
	h.WriteString(id)
	return fmt.Sprintf("%x", h.Sum(nil))
}

type Todo struct {
	Content    string     `json:"content"`
	Status     TodoStatus `json:"status"`
	ActiveForm string     `json:"active_form"`
}

// HasIncompleteTodos returns true if there are any non-completed todos.
func HasIncompleteTodos(todos []Todo) bool {
	for _, todo := range todos {
		if todo.Status != TodoStatusCompleted {
			return true
		}
	}
	return false
}

// SessionTokens holds cumulative token usage for an entire session.
// These counters are persisted with the session and survive restarts.
type SessionTokens struct {
	// InputTokens counts prompt tokens that were neither served from
	// nor written to the provider's prompt cache.
	InputTokens int64
	// OutputTokens counts all tokens generated by the model.
	OutputTokens int64
	// CacheReadTokens counts prompt tokens served from the provider's
	// prompt cache.
	CacheReadTokens int64
	// CacheCreationTokens counts prompt tokens written to the
	// provider's prompt cache.
	CacheCreationTokens int64
}

// TotalPromptTokens returns the total number of prompt tokens sent to
// the provider across the session, including cache reads and cache
// creation.
func (t SessionTokens) TotalPromptTokens() int64 {
	return t.InputTokens + t.CacheReadTokens + t.CacheCreationTokens
}

// CacheHitRate returns the fraction (0..1) of prompt tokens served from
// the provider's prompt cache, or 0 when no prompt tokens were sent.
func (t SessionTokens) CacheHitRate() float64 {
	total := t.TotalPromptTokens()
	if total == 0 {
		return 0
	}
	return float64(t.CacheReadTokens) / float64(total)
}

type Session struct {
	ID               string
	ParentSessionID  string
	Title            string
	MessageCount     int64
	PromptTokens     int64
	CompletionTokens int64
	EstimatedUsage   bool
	SummaryMessageID string
	Cost             float64
	Todos            []Todo
	// DisabledSkills lists the skills this session opted out of, on top
	// of (and independent from) the global options.disabled_skills
	// default a new session is seeded from.
	DisabledSkills []string
	CreatedAt      int64
	UpdatedAt      int64
	// Totals carries cumulative token usage for the whole session. It
	// is persisted with the session.
	Totals SessionTokens
}

type Service interface {
	pubsub.Subscriber[Session]
	Create(ctx context.Context, title string) (Session, error)
	CreateTitleSession(ctx context.Context, parentSessionID string) (Session, error)
	CreateTaskSession(ctx context.Context, toolCallID, parentSessionID, title string) (Session, error)
	Get(ctx context.Context, id string) (Session, error)
	GetLast(ctx context.Context) (Session, error)
	List(ctx context.Context) ([]Session, error)
	Save(ctx context.Context, session Session) (Session, error)
	SetDisabledSkills(ctx context.Context, id string, names []string) error
	UpdateTitleAndUsage(ctx context.Context, sessionID, title string, tokens SessionTokens, cost float64) error
	Rename(ctx context.Context, id string, title string) error
	Delete(ctx context.Context, id string) error

	// Agent tool session management
	CreateAgentToolSessionID(messageID, toolCallID string) string
	ParseAgentToolSessionID(sessionID string) (messageID string, toolCallID string, ok bool)
	IsAgentToolSession(sessionID string) bool
}

type service struct {
	*pubsub.Broker[Session]
	db *sql.DB
	q  *db.Queries

	// defaultDisabledSkills is consulted for sessions that never stored
	// their own skill opt-outs (rows written before per-session skills
	// existed). Such a session inherits the global
	// options.disabled_skills default instead of silently re-enabling every
	// globally disabled skill. Nil means no fallback.
	defaultDisabledSkills func() []string

	// Estimated usage stays in memory so fetch-modify-save paths (e.g.,
	// updating todos or parent-session cost) do not rebuild a session from
	// SQLite and incorrectly clear the UI "~" marker.
	estimatedUsageMu sync.RWMutex
	estimatedUsage   map[string]bool
}

// Option configures a session service.
type Option func(*service)

// WithDefaultDisabledSkills sets the provider consulted for sessions that
// never stored their own skill opt-outs, so legacy rows keep inheriting the
// global options.disabled_skills default.
func WithDefaultDisabledSkills(fn func() []string) Option {
	return func(s *service) {
		s.defaultDisabledSkills = fn
	}
}

func (s *service) Create(ctx context.Context, title string) (Session, error) {
	dbSession, err := s.q.CreateSession(ctx, db.CreateSessionParams{
		ID:    uuid.New().String(),
		Title: title,
	})
	if err != nil {
		return Session{}, err
	}
	session := s.fromDBItem(dbSession)
	s.Publish(pubsub.CreatedEvent, session)
	event.SessionCreated()
	return session, nil
}

func (s *service) CreateTaskSession(ctx context.Context, toolCallID, parentSessionID, title string) (Session, error) {
	dbSession, err := s.q.CreateSession(ctx, db.CreateSessionParams{
		ID:              toolCallID,
		ParentSessionID: sql.NullString{String: parentSessionID, Valid: true},
		Title:           title,
	})
	if err != nil {
		return Session{}, err
	}
	session := s.fromDBItem(dbSession)
	s.Publish(pubsub.CreatedEvent, session)
	return session, nil
}

func (s *service) CreateTitleSession(ctx context.Context, parentSessionID string) (Session, error) {
	dbSession, err := s.q.CreateSession(ctx, db.CreateSessionParams{
		ID:              "title-" + parentSessionID,
		ParentSessionID: sql.NullString{String: parentSessionID, Valid: true},
		Title:           "Generate a title",
	})
	if err != nil {
		return Session{}, err
	}
	session := s.fromDBItem(dbSession)
	s.Publish(pubsub.CreatedEvent, session)
	return session, nil
}

func (s *service) Delete(ctx context.Context, id string) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("beginning transaction: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck

	qtx := s.q.WithTx(tx)

	dbSession, err := qtx.GetSessionByID(ctx, id)
	if err != nil {
		return err
	}
	if err = qtx.DeleteSessionMessages(ctx, dbSession.ID); err != nil {
		return fmt.Errorf("deleting session messages: %w", err)
	}
	if err = qtx.DeleteSessionFiles(ctx, dbSession.ID); err != nil {
		return fmt.Errorf("deleting session files: %w", err)
	}
	if err = qtx.DeleteSession(ctx, dbSession.ID); err != nil {
		return fmt.Errorf("deleting session: %w", err)
	}
	if err = tx.Commit(); err != nil {
		return fmt.Errorf("committing transaction: %w", err)
	}

	session := s.fromDBItem(dbSession)
	s.clearEstimatedUsageState(dbSession.ID)
	s.Publish(pubsub.DeletedEvent, session)
	event.SessionDeleted()
	return nil
}

func (s *service) Get(ctx context.Context, id string) (Session, error) {
	dbSession, err := s.q.GetSessionByID(ctx, id)
	if err != nil {
		return Session{}, err
	}
	session := s.fromDBItem(dbSession)
	s.applyEstimatedUsageState(&session)
	return session, nil
}

func (s *service) GetLast(ctx context.Context) (Session, error) {
	dbSession, err := s.q.GetLastSession(ctx)
	if err != nil {
		return Session{}, err
	}
	session := s.fromDBItem(dbSession)
	s.applyEstimatedUsageState(&session)
	return session, nil
}

func (s *service) Save(ctx context.Context, session Session) (Session, error) {
	todosJSON, err := marshalTodos(session.Todos)
	if err != nil {
		return Session{}, err
	}
	disabledSkillsJSON, err := marshalDisabledSkills(session.DisabledSkills)
	if err != nil {
		return Session{}, err
	}

	dbSession, err := s.q.UpdateSession(ctx, db.UpdateSessionParams{
		ID:                  session.ID,
		Title:               session.Title,
		PromptTokens:        session.PromptTokens,
		CompletionTokens:    session.CompletionTokens,
		TotalInputTokens:    session.Totals.InputTokens,
		TotalOutputTokens:   session.Totals.OutputTokens,
		CacheReadTokens:     session.Totals.CacheReadTokens,
		CacheCreationTokens: session.Totals.CacheCreationTokens,
		SummaryMessageID: sql.NullString{
			String: session.SummaryMessageID,
			Valid:  session.SummaryMessageID != "",
		},
		Cost: session.Cost,
		Todos: sql.NullString{
			String: todosJSON,
			Valid:  todosJSON != "",
		},
		DisabledSkills: sql.NullString{
			String: disabledSkillsJSON,
			Valid:  disabledSkillsJSON != "",
		},
	})
	if err != nil {
		return Session{}, err
	}
	estimatedUsage := session.EstimatedUsage
	s.setEstimatedUsageState(session.ID, estimatedUsage)
	session = s.fromDBItem(dbSession)
	session.EstimatedUsage = estimatedUsage
	s.Publish(pubsub.UpdatedEvent, session)
	return session, nil
}

// UpdateTitleAndUsage updates only the title and usage fields atomically.
// This is safer than fetching, modifying, and saving the entire session.
// tokens are added to the session's cumulative counters. The context
// prompt counter keeps the previous title-call behavior of excluding
// cache reads.
func (s *service) UpdateTitleAndUsage(ctx context.Context, sessionID, title string, tokens SessionTokens, cost float64) error {
	if err := s.q.UpdateSessionTitleAndUsage(ctx, db.UpdateSessionTitleAndUsageParams{
		ID:                  sessionID,
		Title:               title,
		PromptTokens:        tokens.InputTokens + tokens.CacheCreationTokens,
		CompletionTokens:    tokens.OutputTokens,
		TotalInputTokens:    tokens.InputTokens,
		TotalOutputTokens:   tokens.OutputTokens,
		CacheReadTokens:     tokens.CacheReadTokens,
		CacheCreationTokens: tokens.CacheCreationTokens,
		Cost:                cost,
	}); err != nil {
		return err
	}
	s.publishSessionUpdate(ctx, sessionID)
	return nil
}

// SetDisabledSkills replaces a session's per-session disabled-skill set and
// publishes the updated session. It writes only the disabled_skills column
// so a concurrent title/usage update cannot be clobbered. Names are stored
// sorted so the persisted value is deterministic, and an explicitly empty
// set is stored as `[]` rather than NULL so it stays distinguishable from a
// legacy row that inherits the global default.
func (s *service) SetDisabledSkills(ctx context.Context, id string, names []string) error {
	if names == nil {
		names = []string{}
	}
	disabledSkillsJSON, err := marshalDisabledSkills(names)
	if err != nil {
		return err
	}
	rows, err := s.q.UpdateSessionDisabledSkills(ctx, db.UpdateSessionDisabledSkillsParams{
		ID: id,
		DisabledSkills: sql.NullString{
			String: disabledSkillsJSON,
			Valid:  disabledSkillsJSON != "",
		},
	})
	if err != nil {
		return err
	}
	if rows == 0 {
		return sql.ErrNoRows
	}
	s.publishSessionUpdate(ctx, id)
	return nil
}

// Rename updates only the title of a session without touching updated_at or
// usage fields.
func (s *service) Rename(ctx context.Context, id string, title string) error {
	if err := s.q.RenameSession(ctx, db.RenameSessionParams{
		ID:    id,
		Title: title,
	}); err != nil {
		return err
	}
	s.publishSessionUpdate(ctx, id)
	return nil
}

func (s *service) List(ctx context.Context) ([]Session, error) {
	dbSessions, err := s.q.ListSessions(ctx)
	if err != nil {
		return nil, err
	}
	sessions := make([]Session, len(dbSessions))
	for i, dbSession := range dbSessions {
		sessions[i] = s.fromDBItem(dbSession)
		s.applyEstimatedUsageState(&sessions[i])
	}
	return sessions, nil
}

// publishSessionUpdate re-fetches a session and publishes an UpdatedEvent so
// that UI subscribers reflect title or usage changes.
func (s *service) publishSessionUpdate(ctx context.Context, sessionID string) {
	session, err := s.Get(ctx, sessionID)
	if err != nil {
		slog.Error("Failed to re-fetch session for event publish", "error", err, "sessionID", sessionID)
		return
	}
	s.Publish(pubsub.UpdatedEvent, session)
}

func (s *service) applyEstimatedUsageState(session *Session) {
	s.estimatedUsageMu.RLock()
	session.EstimatedUsage = s.estimatedUsage[session.ID]
	s.estimatedUsageMu.RUnlock()
}

func (s *service) setEstimatedUsageState(sessionID string, estimatedUsage bool) {
	s.estimatedUsageMu.Lock()
	defer s.estimatedUsageMu.Unlock()
	if estimatedUsage {
		s.estimatedUsage[sessionID] = true
		return
	}
	delete(s.estimatedUsage, sessionID)
}

func (s *service) clearEstimatedUsageState(sessionID string) {
	s.estimatedUsageMu.Lock()
	delete(s.estimatedUsage, sessionID)
	s.estimatedUsageMu.Unlock()
}

func (s *service) fromDBItem(item db.Session) Session {
	todos, err := unmarshalTodos(item.Todos.String)
	if err != nil {
		slog.Error("Failed to unmarshal todos", "session_id", item.ID, "error", err)
	}
	disabledSkills, err := unmarshalDisabledSkills(item.DisabledSkills.String)
	if err != nil {
		slog.Error("Failed to unmarshal disabled skills", "session_id", item.ID, "error", err)
	}
	// A NULL column means the session never stored its own opt-outs, so the
	// global default still applies to it.
	if !item.DisabledSkills.Valid && s.defaultDisabledSkills != nil {
		disabledSkills = s.defaultDisabledSkills()
	}
	return Session{
		ID:               item.ID,
		ParentSessionID:  item.ParentSessionID.String,
		Title:            item.Title,
		MessageCount:     item.MessageCount,
		PromptTokens:     item.PromptTokens,
		CompletionTokens: item.CompletionTokens,
		SummaryMessageID: item.SummaryMessageID.String,
		Cost:             item.Cost,
		Todos:            todos,
		DisabledSkills:   disabledSkills,
		CreatedAt:        item.CreatedAt,
		UpdatedAt:        item.UpdatedAt,
		Totals: SessionTokens{
			InputTokens:         item.TotalInputTokens,
			OutputTokens:        item.TotalOutputTokens,
			CacheReadTokens:     item.CacheReadTokens,
			CacheCreationTokens: item.CacheCreationTokens,
		},
	}
}

func marshalTodos(todos []Todo) (string, error) {
	if len(todos) == 0 {
		return "", nil
	}
	data, err := json.Marshal(todos)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

func unmarshalTodos(data string) ([]Todo, error) {
	if data == "" {
		return []Todo{}, nil
	}
	var todos []Todo
	if err := json.Unmarshal([]byte(data), &todos); err != nil {
		return []Todo{}, err
	}
	return todos, nil
}

// normalizeDisabledSkills sorts and deduplicates a disabled-skill set so
// the persisted JSON and the in-memory value agree on one canonical order.
// A non-nil input always yields a non-nil result, so an explicitly empty set
// stays distinguishable from a session that never stored one (nil).
func normalizeDisabledSkills(names []string) []string {
	if names == nil {
		return nil
	}
	cleaned := slices.Compact(slices.Sorted(slices.Values(names)))
	if cleaned == nil {
		cleaned = []string{}
	}
	return cleaned
}

// marshalDisabledSkills encodes a disabled-skill set for storage. A nil set
// is stored as SQL NULL, meaning "the session never chose, inherit the
// global default"; an explicitly empty set is stored as `[]`.
func marshalDisabledSkills(names []string) (string, error) {
	if names == nil {
		return "", nil
	}
	data, err := json.Marshal(normalizeDisabledSkills(names))
	if err != nil {
		return "", err
	}
	return string(data), nil
}

func unmarshalDisabledSkills(data string) ([]string, error) {
	if data == "" {
		return nil, nil
	}
	var names []string
	if err := json.Unmarshal([]byte(data), &names); err != nil {
		return nil, err
	}
	return normalizeDisabledSkills(names), nil
}

// NewService creates a session service. Options are optional so existing
// callers keep working; see [WithDefaultDisabledSkills].
func NewService(q *db.Queries, conn *sql.DB, opts ...Option) Service {
	broker := pubsub.NewBroker[Session]()
	s := &service{
		Broker:         broker,
		db:             conn,
		q:              q,
		estimatedUsage: make(map[string]bool),
	}
	for _, opt := range opts {
		opt(s)
	}
	return s
}

// CreateAgentToolSessionID creates a session ID for agent tool sessions using the format "messageID$$toolCallID"
func (s *service) CreateAgentToolSessionID(messageID, toolCallID string) string {
	return fmt.Sprintf("%s$$%s", messageID, toolCallID)
}

// ParseAgentToolSessionID parses an agent tool session ID into its components
func (s *service) ParseAgentToolSessionID(sessionID string) (messageID string, toolCallID string, ok bool) {
	parts := strings.Split(sessionID, "$$")
	if len(parts) != 2 {
		return "", "", false
	}
	return parts[0], parts[1], true
}

// IsAgentToolSession checks if a session ID follows the agent tool session format
func (s *service) IsAgentToolSession(sessionID string) bool {
	_, _, ok := s.ParseAgentToolSessionID(sessionID)
	return ok
}
